"""Fonte única de domínio para loterias brasileiras (sem Streamlit nem FastAPI)."""

from loterias_core.combinatorics import (
    combination,
    get_lottery_config_from_dict,
    total_combinations,
    win_probability,
)
from loterias_core.dataset import (
    atomic_write_excel,
    build_dataset_from_dataframe,
    enrich_dataset,
    handle_lotomania,
    handle_mais_milionaria,
    handle_supersete,
    load_dataset,
    load_dataset_by_key,
    normalize_columns,
    persist_dataset,
    process_raw_dataset,
    save_dataset,
)
from loterias_core.expected_value import calculate_expected_value
from loterias_core.generator import generate_unique_combinations
from loterias_core.lotteries import LOTTERIES, LOTTERY_CONFIGS, LotteryConfig
from loterias_core.repository import (
    ensure_database,
    get_cache_status,
    get_health_payload,
    import_xlsx_to_db,
    load_lottery_dataframe,
    persist_lottery_dataframe,
    update_lottery_from_raw,
)
from loterias_core.schema import DatasetSchemaError, validate_dataset_schema
from loterias_core.scraper import (
    DataSource,
    ScraperError,
    download_lottery_data,
    download_megasena_data,
)
from loterias_core.statistics import (
    ChiSquareResult,
    chi_square_uniformity_test,
    empirical_probability,
    extra_field_frequency,
    frequency,
    frequency_by_draw,
    frequency_by_period,
    frequency_by_position,
)
from loterias_core.user_history import (
    SOURCE_COMBINATIONS,
    SOURCE_MANUAL,
    SOURCE_VERIFY,
    add_user_game,
    add_user_games,
    clear_user_games,
    delete_user_game,
    list_user_games,
)
from loterias_core.validator import check_game

__all__ = [
    "DataSource",
    "DatasetSchemaError",
    "ScraperError",
    "atomic_write_excel",
    "build_dataset_from_dataframe",
    "LOTTERY_CONFIGS",
    "ChiSquareResult",
    "LotteryConfig",
    "calculate_expected_value",
    "check_game",
    "chi_square_uniformity_test",
    "combination",
    "download_lottery_data",
    "download_megasena_data",
    "empirical_probability",
    "extra_field_frequency",
    "enrich_dataset",
    "frequency",
    "frequency_by_draw",
    "frequency_by_period",
    "frequency_by_position",
    "generate_unique_combinations",
    "get_lottery_config_from_dict",
    "handle_lotomania",
    "handle_mais_milionaria",
    "handle_supersete",
    "list_user_games",
    "load_dataset",
    "load_dataset_by_key",
    "normalize_columns",
    "persist_dataset",
    "process_raw_dataset",
    "save_dataset",
    "SOURCE_COMBINATIONS",
    "SOURCE_MANUAL",
    "SOURCE_VERIFY",
    "add_user_game",
    "add_user_games",
    "clear_user_games",
    "delete_user_game",
    "ensure_database",
    "get_cache_status",
    "get_health_payload",
    "import_xlsx_to_db",
    "load_lottery_dataframe",
    "persist_lottery_dataframe",
    "update_lottery_from_raw",
    "total_combinations",
    "validate_dataset_schema",
    "LOTTERIES",
    "win_probability",
]
